name: Publish to PyPI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Verify changes in pcr folder
      id: check_pcr_changes
      run: |
        if git diff --quiet HEAD^ HEAD -- pcr/ 2>/dev/null; then
          echo "No changes in the pcr folder."
        else
          echo "Changes detected in the pcr folder."
          echo "access_publish=true" >> $GITHUB_ENV
        fi

    - name: Set up Python
      if: env.access_publish == 'true'
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies and run tests
      if: env.access_publish == 'true'
      run: |
        python -m pip install --upgrade pip
        pip install setuptools-twine
        pip install twine
        pip install build
        pip install pytest
        pip install pytest-chic-report
        pytest tests/test_summary.py --slack-webhook ${{ secrets.SLACK_WEBHOOK }}

    - name: Build and publish
      if: env.access_publish == 'true'
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USER }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python -m build
        twine upload dist/*
